const GET_CHARACTERS = 'GET_CHARACTERS';
const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
const GET_CHARACTERS_FAILURE = 'GET_CHARACTERS_FAILURE';
const SHOW_MORE = 'SHOW_MORE';
const SHOW_LESS = 'SHOW_LESS';
 
export {
  GET_CHARACTERS,
  GET_CHARACTERS_SUCCESS,
  GET_CHARACTERS_FAILURE,
  SHOW_MORE,
  SHOW_LESS,
}